### ISSUE TITLE
threshold line in manhattan plots

### ISSUE THREAD

**Issue by jahneldardavik** [jendelman/GWASpoly#1]
Hello,
I am using GWASpoly version 2.03.
In the manual it says that if the 'data' is the output from 'set.threshold', then the threshold will be displayed on the manhattan plot. That does noe occur when I run it. 

data3 <- set.threshold(data3,method="M.eff",level=0.05)
manhattan.plot(data3)

Gives the attached plot
![Skjermbilde](https://user-images.githubusercontent.com/25763942/109811919-b5c5a900-7c2b-11eb-9ce2-de49c28649e4.PNG)

**Comment by jendelman** [comment]
Resolved.
