### ISSUE TITLE
How to extract the geno.code file for VCF2dosage?

### ISSUE THREAD

**Issue by SHU-YUN** [jendelman/GWASpoly#11]
Dear,
I am trying to apply this wonderful package for GWAS analysis in orchids, an autotetraploid population. The first thing I am going to do is prepare the dosage file by the "VCF2dosage" function which is described as VCF2dosage(VCF.file, dosage.file, geno.code, ploidy, samples=NULL,min.DP=1, max.missing, min.minor=5) in the manuscript. The following command "vcftools --vcf <your_vcf> --extract-FORMAT-info GT --out <prefix>" was applied to create the geno.code file from the vcf file (##fileformat=VCFv4.2). 
However, I got a warning sign as followed
"Error in VCF2dosage("/Volumes/Storge_room/NCHU/sample_all_joint_variant_SNPs_filtered_bqsr_snps_subset_0.0012.vcf",  : 
  geno.code %in% c("GT", "DS") is not TRUE"
Did the geno.code file I applied is not right? how to fix the problem? Really appreciated any suggestions.

The 

Best,
Shu-Yun Chen

**Comment by jendelman** [comment]
Hello,
There are two options for the geno.code argument. It must be either "GT" or "DS", depending on whether you want to use the "GT" or "DS" field for each sample in the VCF file. It looks like you are intending to use GT, but perhaps you did not specify geno.code="GT" ?

Jeff
