### ISSUE TITLE
How to solve the tetraploid genotype problem （0，1，2，3，4）

### ISSUE THREAD

**Issue by yt619** [jendelman/GWASpoly#12]
Dear，
I am trying to use this software to perform a genome-wide association analysis of tetraploids. I obtained the gvcf files of each sample through GATK, merged them, and performed conventional filtering on the vcf files. But when I transformed vcf through VCF2dosage, I found that I could not get the genotypes of 0, 1, 2, 3, and 4 in extdata.  I can only get the genotypes of 0, 1, and 2. Is this a problem when I filter vcf? Or should we take a special approach when merging gvcf files?

VCF2dosage('gwas328.snp_filtered_maf0.1geno0.9.vcf', 'gwas328.snp_filtered_maf0.1geno0.9.csv', geno.code="GT", 4, samples=NULL,min.DP = 1,max.missing=0.1,min.minor = 5)

I'm not sure how to get a correct genotype file, I hope you can help with this, thanks a lot.

Detection of variation is performed following the best practice workflow recommended by GATK (18) (version 3.8.1). In brief, the variants were called for each accession by GATK Haplotype Caller. **A joint genotyping step for comprehensive variations union was performed on the gVCF, the ploidy was set 2 or 4 according to the ploidy of accessions.** In the filtering step, the SNP filter
expression was set as QD < 2.0 || MQ < 20.0 || FS > 60.0 || SOR > 3.0 || MQRankSum < − 12.5 || ReadPosRankSum < − 8.0, and the InDel filter expression was set as QD < 2.0 || FS > 200.0 || MQ < 40.0 || SOR > 10.0 || ReadPosRankSum < − 20.0.

The above is the method of an article, which used GWASploy for analysis, where the merging step is not clearly described.
Resequencing and genome-wide association studies of autotetraploid potato

The Best,
Tuo Yang

**Comment by jendelman** [comment]
Hello,
Are you sure that you have tetraploid genotype calls in your VCF? You can visually inspect the first few variants to see. 
If they are tetraploid, did you set ploidy=4 in VCF2dosage?
