### ISSUE TITLE
Any p value for diplo-general and diplo-additive for ploidy 4 using fit.QTL function

### ISSUE THREAD

**Issue by huw143** [jendelman/GWASpoly#16]
Dear Jeffrey,

It looks like that the fit.QTL function is not working for diplo-general and diplo-additive for ploidy 4 when I look for p value based on backward elimination, do you have any idea for this?

Please see below for details:

Error in fit.QTL(data = data_4, trait = plant_height,  : 
  qtl$Model %in% c("additive", "general", paste(1:(data@ploidy/2),  .... are not all TRUE

Kind regards,

Tiger

**Comment by jendelman** [comment]
Thank you for pointing this out. I don't use those models anymore and would not recommend them for general use, so I never checked this when developing fit.QTL. I do not have plans to fix this error at this time.
