### ISSUE TITLE
Additional random effects with covariance matrices

### ISSUE THREAD

**Issue by TrineAalborg** [jendelman/GWASpoly#23]
Hi,

I am working on a GWAS analysis of some field data on tetraploid potatoes. I have a model with fixed effects based on the experimental setup and have included the LOCO covariance matrix to account for population structure. However, I still see some inflation in the QQ plots for some phenotypes e.g. plant cover and emergence, why I'd like to include a random spatial effect in the model with a covariance matrix based on the spatial effects between nearest neighbors in the field grid to account for neighbor effects. Given the structure of the spatial effect matrix, principal components each explain only a small fraction of the total variance (< 3 %), why including the PCs as fixed effects (P + K) does not seem optimal. Based on the manual and vignette, I can't find an option for including random effects in the GWASpoly model, besides the kinship matrix. Is it possible to somehow include the spatial effects in the model as a random effect? Or do you have an alternative suggestion for how to incorporate the spatial effects?

Thank you for your time and advice,

Sincerely 
Trine Aalborg

**Comment by jendelman** [comment]
Hello, GWASpoly cannot accommodate additional random effects. I suggest calculating adjusted phenotypes with a spatial model using some other software first, and then use those results in GWASpoly.
