### ISSUE TITLE
Is there a way to make the model not correct by kinship?

### ISSUE THREAD

**Issue by Hidroxiapatito** [jendelman/GWASpoly#24]
Like I salid: Is there a way to make the model NOT correct by kinship?

I see that in the GWASpoly funtion the "data" parameter needs an object of class "GWASpoly.K". I've tried modifying that object but I just get errors. The only solution I've come up with is to use an all zeroes matrix, since I'm afraid a diagonal matrix might capture residual effects.

Is there any other way I might be missing?

**Comment by jendelman** [comment]
Hello, GWASpoly does not have a method for GWAS without a K matrix.
