### ISSUE TITLE
Needing a constructor for GWASpoly.data

### ISSUE THREAD

**Issue by ne1s0n** [jendelman/GWASpoly#6]
Currently the only way to obtain an instance of GWASpoly.data objects is to have files read via read.GWASpoly function. This can be very inefficient, especially if I already have the data loaded in the pipeline (I currently save the data to a tempfile which is then deleted).

A constructor function with a signature

`build.GWASpoly (phenotype, map, genotype, ploidy, fixed)`

should be easy to implement.

**Comment by jendelman** [comment]
Thank you for this suggestion. You are right that this is good practice for object-oriented programming, but since I don't think there is much demand for this feature, I would suggest you implement this locally for your own use.
