### ISSUE TITLE
Installation of the Package

### ISSUE THREAD

**Issue by acefestus** [jendelman/GWASpoly#7]
Hi! I am trying to install this package but kept getting the error message that the package is not available for the latest version of R.

How can I move ahead, please?

**Comment by mcaraza-harter** [comment]
Hi! 
GWASpoly should be able to be installed with the latest R version 4.1.2 without a problem. Please check which version of R you have, maybe try installing the latest version.

**Comment by acefestus** [comment]
Hi @mcaraza-harter Thanks for responding. I was able to install it. I was trying to compute marker significance scores
using GWASpoly to test non-additive models. 

I was getting the error in the attached image. How can I resolve it, please?
<img width="1440" alt="Screenshot 2022-01-01 at 04 40 55" src="https://user-images.githubusercontent.com/50450408/147843457-f553ddb5-0a47-4cee-93a6-53a928d28c8f.png">

**Comment by jendelman** [comment]
Hello, glad to hear the installation problem was fixed. This new error message makes me think there is something wrong with your marker or phenotype data. I would need to see the dataset to troubleshoot.
