### ISSUE TITLE
Error with read.GWASpoly

### ISSUE THREAD

**Issue by M-C-T** [jendelman/GWASpoly#8]
Hi

I am getting this error when reading in with the read.GWASpoly function, but didn't used to get this problem:

> data <- read.GWASpoly(ploidy=4, pheno.file= phenofile, geno.file= genofile,
+                       format="AB", n.traits=6, delim=",")
Error in read.table(file = geno.file, header = T, as.is = T, check.names = F,  : 
  'file' must be a character string or connection

The csv for both geno and pheno seem to read in fine as expected, but it doesn't now seem to like the genofile.  I expect that I am doing something silly with the geno csv formatting, or with something, and did have to reinstall everything recently following a computer crash, but I am a little lost as what I need to do to solve this.  My version of R is up to date, but it also didn't like installing the package until following your devtools method .

Thanks in advance, and I can send you the csv files too

Regards

Michael

**Comment by jendelman** [comment]
Michael,
I am not sure what could be causing this error. Can you send me the CSV file to troubleshoot?

Jeff

**Comment by M-C-T** [comment]
Hi Jeff

Thank you for your reply, and I hope I have correctly attached the geno CSV file for you to view below.  

I still haven't figured out what I am now doing wrong, and have been sat trying to import this via the read.table function to the 'genofile', but that is taking forever to load, and I haven't been able to try that with the readGWASpoly function yet (literally sat doing that now).

Michael

[GWAS Geno Amended.csv](https://github.com/jendelman/GWASpoly/files/8201485/GWAS.Geno.Amended.csv)

**Comment by jendelman** [comment]
Michael,
The read.csv function reads your file just fine, but read.table will not, which is very strange. read.table just hangs and never finishes. I have not encountered this problem before and would suggest posting the issue on a more general website for R. The problem goes beyond what I can fix within GWASpoly.

**Comment by M-C-T** [comment]
I did feel that this was not a problem with your programme, because it worked so well before. It is no doubt something stupid I have done to the formatting while recovering the files after PC issues.  I will try and change the files relating to this again, and if the problem persists, post the problem as you have stated re-read.table function on R community.  A definite eye opener to my computing abilities! 

Your help and time is most appreciated

Regards

Michael
