### ISSUE TITLE
LD.plot optimization

### ISSUE THREAD

**Issue by mchizk1** [jendelman/GWASpoly#9]
Hello Dr. Endelman, I'm a big fan of the package and have really enjoyed using it in my own research! I've got one slight suggestion for improvement on the `LD.plot()` function. Currently, as I understand it, LD.plot.R runs correlations on all loci provided, but only models/plots a small sampling of these resulting correlations. This may test or exceed the limits on some lower-memory machines. A lot of memory and time could be spared by sampling SNPs prior to running the correlations and distance matrix.  However, the `max.pair` argument would unfortunately need to become `max.loci` or something like that. Hope this is helpful!

**Comment by jendelman** [comment]
Thank you for this suggestion! I added the argument "max.loci" for version 2.11 of the package.
